-- MySQL dump 10.13  Distrib 8.0.17, for Win64 (x86_64)
--
-- Host: localhost    Database: online_quiz
-- ------------------------------------------------------
-- Server version	8.0.17

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `os`
--

DROP TABLE IF EXISTS `os`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `os` (
  `qid` int(2) DEFAULT NULL,
  `question` varchar(800) DEFAULT NULL,
  `option1` varchar(90) DEFAULT NULL,
  `option2` varchar(90) DEFAULT NULL,
  `option3` varchar(90) DEFAULT NULL,
  `option4` varchar(90) DEFAULT NULL,
  `answer` int(2) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `os`
--

LOCK TABLES `os` WRITE;
/*!40000 ALTER TABLE `os` DISABLE KEYS */;
INSERT INTO `os` VALUES (1,'System calls are invoked by using','Software Interrupts','Polling','Indirect Jump','A priviledged instruction',1),(2,'Spooling is','The rewinding of tapes after processing','temporary storage-management of output to output devices until they can cope with it','The recording of all user activities in a log file','None Of The Above',2),(3,'Which of the following is NOT a solution for the critical section problem?','Monitor','Semaphore','Segmentation','Critical Region Constructs',3),(4,'Which of the following is NOT a solution for the critical section problem?','Thrashing','Belady\'s Anamoly','Reentrancy','None Of The Above',1),(5,' Object modules generated by assemblers may contain unresolved references. These are resolved using other object modules by the','Linker','Loader','Debugger','Compiler',1),(6,'Where does swap space resides?','RAM','ROM','Disk','On-Chip Cache',3),(7,'Transfer of information to and from main memory takes place in terms of','Bits','Bytes','Words','Nibbles',3),(8,'While running DOS on a PC, which command would be used to duplicate the entire diskette?','Copy','DiskCopy','mkdir','Copy filename1 filename2',2),(9,'Page fault occurs when','The page is corrupted by application software','The page is in main memory','The page is not in main memory','One tries to divide a number by 0',3),(10,'The process which requires saving the state of the old process and loading the saved state for the new process when switching occurs is known as','Dispatcher','CPU Scheduling','Context Switch','Fragmentation',3);
/*!40000 ALTER TABLE `os` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2019-11-01 16:24:04
